#!/usr/bin/env bash
set -euo pipefail

# Measures sudo performance and reports tuning impact.
# MODE=sequential: apply settings in order and report each step.
# MODE=search: pick only settings that improve performance (greedy forward search).
# Default behavior restores the original /etc/sudoers.d/99-tuning at exit.
# Set KEEP_FINAL=1 to keep the final generated tuning file.

ITERATIONS="${ITERATIONS:-100}"
BENCH_RUNS="${BENCH_RUNS:-3}"
KEEP_FINAL="${KEEP_FINAL:-0}"
MODE="${MODE:-sequential}"
TUNING_FILE="/etc/sudoers.d/99-tuning"

if [[ "${EUID}" -ne 0 ]]; then
  echo "This script must run as root." >&2
  echo "Try: sudo bash sudo-tuning.sh" >&2
  exit 1
fi

if ! command -v visudo >/dev/null 2>&1; then
  echo "visudo is required but was not found." >&2
  exit 1
fi

# Each entry: "sudoers_line|label"
SETTINGS=(
  "Defaults timestamp_timeout=30|timestamp_timeout=30"
  "Defaults timestamp_type=global|timestamp_type=global"
  "Defaults !use_pty|!use_pty"
  "Defaults !pam_session|!pam_session"
  "Defaults !pam_setcred|!pam_setcred"
  "Defaults !syslog|!syslog"
  "Defaults !log_allowed|!log_allowed"
  "Defaults !log_denied|!log_denied"
  "Defaults !env_reset|!env_reset"
  "Defaults !authenticate|!authenticate"
)

SETTING_COUNT="${#SETTINGS[@]}"

if [[ "${MODE}" != "sequential" && "${MODE}" != "search" ]]; then
  echo "Invalid MODE: ${MODE}" >&2
  echo "Valid values: sequential, search" >&2
  exit 1
fi

HAD_ORIGINAL=0
ORIGINAL_BACKUP="$(mktemp)"
WORK_BACKUP="$(mktemp)"

restore_original() {
  if [[ "${HAD_ORIGINAL}" -eq 1 ]]; then
    cp -f "${ORIGINAL_BACKUP}" "${TUNING_FILE}"
    chmod 440 "${TUNING_FILE}"
  else
    rm -f "${TUNING_FILE}"
  fi
}

cleanup() {
  local ec="$?"
  if [[ "${KEEP_FINAL}" != "1" ]]; then
    restore_original
  fi
  rm -f "${ORIGINAL_BACKUP}" "${WORK_BACKUP}"
  exit "${ec}"
}
trap cleanup EXIT

if [[ -f "${TUNING_FILE}" ]]; then
  HAD_ORIGINAL=1
  cp -f "${TUNING_FILE}" "${ORIGINAL_BACKUP}"
fi

# Start from baseline: no custom tuning file.
rm -f "${TUNING_FILE}"
visudo -cf /etc/sudoers >/dev/null

bench_once() {
  local t
  TIMEFORMAT='%R'
  t=$( { time (for ((i=1; i<=ITERATIONS; i++)); do sudo true; done) >/dev/null; } 2>&1 )
  printf '%s\n' "${t}"
}

init_tuning_file() {
  cat > "${TUNING_FILE}" <<'EOF'
# Auto-generated by sudo-tuning.sh
EOF
  chmod 440 "${TUNING_FILE}"
  visudo -cf /etc/sudoers >/dev/null
}

rebuild_tuning_file_from_indexes() {
  local -n idx_ref=$1
  local idx
  local line

  init_tuning_file
  for idx in "${idx_ref[@]}"; do
    line="${SETTINGS[idx]%%|*}"
    printf '%s\n' "${line}" >> "${TUNING_FILE}"
  done

  if ! visudo -cf /etc/sudoers >/dev/null 2>&1; then
    return 1
  fi
  return 0
}

bench_avg() {
  local sum="0"
  local current
  local i
  for ((i=1; i<=BENCH_RUNS; i++)); do
    current="$(bench_once)"
    sum="$(awk -v a="${sum}" -v b="${current}" 'BEGIN { printf "%.6f", a + b }')"
  done
  awk -v s="${sum}" -v n="${BENCH_RUNS}" 'BEGIN { printf "%.6f", s / n }'
}

percent_change() {
  local before="$1"
  local after="$2"
  awk -v b="${before}" -v a="${after}" 'BEGIN { if (b==0) { print "0.00" } else { printf "%.2f", ((b-a)/b)*100 } }'
}

printf 'ITERATIONS=%s, BENCH_RUNS=%s\n' "${ITERATIONS}" "${BENCH_RUNS}"
baseline="$(bench_avg)"
prev="${baseline}"
if [[ "${MODE}" == "sequential" ]]; then
  printf 'MODE=sequential\n'
  printf '| Step | Avg sec | Delta vs baseline (sec) | Improvement vs baseline | Delta vs prev (sec) | Improvement vs prev |\n'
  printf '|---|---:|---:|---:|---:|---:|\n'
  printf '| baseline (before tuning) | %s | 0.000000 | 0.00%% | 0.000000 | 0.00%% |\n' "${baseline}"

  init_tuning_file
  for entry in "${SETTINGS[@]}"; do
    line="${entry%%|*}"
    label="${entry#*|}"

    cp -f "${TUNING_FILE}" "${WORK_BACKUP}"
    printf '%s\n' "${line}" >> "${TUNING_FILE}"

    if ! visudo -cf /etc/sudoers >/dev/null 2>&1; then
      cp -f "${WORK_BACKUP}" "${TUNING_FILE}"
      chmod 440 "${TUNING_FILE}"
      visudo -cf /etc/sudoers >/dev/null
      printf '| %s | skipped | n/a | n/a | n/a | n/a |\n' "${label}"
      continue
    fi

    current="$(bench_avg)"
    delta_base="$(awk -v c="${current}" -v b="${baseline}" 'BEGIN { printf "%.6f", c-b }')"
    delta_prev="$(awk -v c="${current}" -v p="${prev}" 'BEGIN { printf "%.6f", c-p }')"
    imp_base="$(percent_change "${baseline}" "${current}")"
    imp_prev="$(percent_change "${prev}" "${current}")"

    printf '| %s | %s | %s | %s%% | %s | %s%% |\n' \
      "${label}" "${current}" "${delta_base}" "${imp_base}" "${delta_prev}" "${imp_prev}"

    prev="${current}"
  done

  final="${prev}"
else
  printf 'MODE=search\n'
  printf '| Round | Added setting | Avg sec | Delta vs baseline (sec) | Improvement vs baseline | Delta vs prev accepted (sec) | Improvement vs prev accepted |\n'
  printf '|---|---|---:|---:|---:|---:|---:|\n'
  printf '| 0 | baseline (before tuning) | %s | 0.000000 | 0.00%% | 0.000000 | 0.00%% |\n' "${baseline}"

  selected_indexes=()
  accepted_prev="${baseline}"
  round=1

  while true; do
    best_idx=-1
    best_time=""

    for ((i=0; i<SETTING_COUNT; i++)); do
      already_selected=0
      for chosen in "${selected_indexes[@]}"; do
        if [[ "${chosen}" -eq "${i}" ]]; then
          already_selected=1
          break
        fi
      done
      if [[ "${already_selected}" -eq 1 ]]; then
        continue
      fi

      candidate_indexes=("${selected_indexes[@]}" "${i}")
      if ! rebuild_tuning_file_from_indexes candidate_indexes; then
        continue
      fi

      candidate_time="$(bench_avg)"
      if [[ -z "${best_time}" ]] || awk -v c="${candidate_time}" -v b="${best_time}" 'BEGIN {exit !(c<b)}'; then
        best_time="${candidate_time}"
        best_idx="${i}"
      fi
    done

    if [[ "${best_idx}" -lt 0 ]]; then
      break
    fi

    if ! awk -v c="${best_time}" -v p="${accepted_prev}" 'BEGIN {exit !(c<p)}'; then
      break
    fi

    selected_indexes+=("${best_idx}")
    if ! rebuild_tuning_file_from_indexes selected_indexes; then
      echo "Unexpected invalid selected set; stopping search." >&2
      break
    fi

    added_label="${SETTINGS[best_idx]#*|}"
    delta_base="$(awk -v c="${best_time}" -v b="${baseline}" 'BEGIN { printf "%.6f", c-b }')"
    delta_prev="$(awk -v c="${best_time}" -v p="${accepted_prev}" 'BEGIN { printf "%.6f", c-p }')"
    imp_base="$(percent_change "${baseline}" "${best_time}")"
    imp_prev="$(percent_change "${accepted_prev}" "${best_time}")"

    printf '| %s | %s | %s | %s | %s%% | %s | %s%% |\n' \
      "${round}" "${added_label}" "${best_time}" "${delta_base}" "${imp_base}" "${delta_prev}" "${imp_prev}"

    accepted_prev="${best_time}"
    round=$((round + 1))
  done

  if [[ "${#selected_indexes[@]}" -eq 0 ]]; then
    rm -f "${TUNING_FILE}"
    visudo -cf /etc/sudoers >/dev/null
  else
    rebuild_tuning_file_from_indexes selected_indexes >/dev/null
  fi

  final="${accepted_prev}"
  if [[ "${#selected_indexes[@]}" -gt 0 ]]; then
    selected_labels=()
    for idx in "${selected_indexes[@]}"; do
      selected_labels+=("${SETTINGS[idx]#*|}")
    done
    printf '\nSelected settings: %s\n' "$(IFS=', '; echo "${selected_labels[*]}")"
  else
    printf '\nSelected settings: none\n'
  fi
fi

final_imp="$(percent_change "${baseline}" "${final}")"
printf '\nFinal average: %s sec (improvement vs baseline: %s%%)\n' "${final}" "${final_imp}"

if [[ "${KEEP_FINAL}" == "1" ]]; then
  echo "KEEP_FINAL=1: keeping generated ${TUNING_FILE}" >&2
else
  echo "KEEP_FINAL!=1: restoring original ${TUNING_FILE} at exit" >&2
fi
